/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#1c1b1b',
        'tertiary-container': '#444646',
        'primary-fixed-dim': '#bac3ff',
        'outline': '#757685',
        'tertiary-fixed': '#e2e2e2',
        'surface-tint': '#3b52cc',
        'on-secondary-container': '#656464',
        'tertiary': '#2e3030',
        'on-tertiary-fixed-variant': '#454747',
        'on-tertiary-fixed': '#1a1c1c',
        'background': '#fbf9f5',
        'inverse-on-surface': '#f3f0ec',
        'secondary-container': '#e5e2e1',
        'surface-container-low': '#f5f3ef',
        'primary-fixed': '#dee0ff',
        'inverse-primary': '#bac3ff',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#c6c6c7',
        'secondary-fixed': '#e5e2e1',
        'error': '#ba1a1a',
        'on-surface': '#1b1c1a',
        'primary-container': '#1a35b2',
        'outline-variant': '#c5c5d6',
        'surface-container-high': '#eae8e4',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container': '#f0eeea',
        'on-primary-container': '#a1aeff',
        'surface-bright': '#fbf9f5',
        'secondary': '#5f5e5e',
        'on-background': '#1b1c1a',
        'surface-variant': '#e4e2de',
        'secondary-fixed-dim': '#c8c6c5',
        'primary': '#001e8d',
        'on-primary-fixed': '#00105b',
        'on-secondary-fixed-variant': '#474646',
        'on-error': '#ffffff',
        'surface-dim': '#dcdad6',
        'surface-container-highest': '#e4e2de',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#30312e',
        'on-surface-variant': '#444654',
        'on-tertiary-container': '#b3b4b4',
        'on-primary-fixed-variant': '#1c37b3',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'surface': '#fbf9f5',
      },
      borderRadius: {
        'DEFAULT': '0px',
        'lg': '0px',
        'xl': '0px',
        'full': '9999px',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans'],
        'body': ['Inter'],
        'label': ['Space Grotesk'],
      },
    },
  },
  plugins: [],
}
